name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "hellow world"
      - name: Print Goodbye
        run: echo "done bye"
        
