name: Lint Test Deploy
on: push
jobs:
    LintTest:
        runs-on: ubuntu-latest
        steps:
          - name: Clone Repo
            uses: actions/checkout@v3
          - name: Install Dependencies
            run: npm install -g eslint vitest vite eslint-plugin-react
          - name: Lint
            run: eslint --ext .jsx --fix src
            working-directory: fourth-exercise
          - name: Test
            run: vitest run
            working-directory: fourth-exercise
          - name: Build
            run: vite build
            working-directory: fourth-exercise
