name: Lint Test Deploy
on: push
jobs:
    LintTest:
        runs-on: ubuntu-latest
        steps:
          - name: Clone Repo
            uses: actions/checkout@v3
          - name: Install Dependencies
            run: npm ci
            working-directory: fourth-exercise
          - name: Lint
            run: npm run lint
            working-directory: fourth-exercise
          - name: Test
            run: npm run test
            working-directory: fourth-exercise
          - name: Build
            run: npm run build
            working-directory: fourth-exercise
